- Cargo.lock
- Cargo.toml
- README.md
- ci/script.sh
- core/Cargo.toml
- core/src/lib.rs
- core/src/mx.rs
- core/src/smtp.rs
- serverless/Cargo.toml
- src/cli.yml
- src/main.rs
- test_suite/Cargo.toml
- test_suite/src/lib.rs
the `mx` object contains a new field `is_disposable`
BREAKING CHANGE: the `smtp`'s object keys have changed. Instead of
```
{
"deliverable": ...,
"full_inbox": ...,
"has_catch_all": ...
}
```
it now returns 
```
{
"has_full_inbox": ...,
"is_deliverable": ...,
"is_disabled": ...,
"is_catch_all": ...
}
```
where `is_disabled` checks if the address has been disabled/blocked by the email provider
> feat: Add disposable email check

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/lib.rs
- core/src/smtp.rs
- src/main.rs
- test_suite/Cargo.toml
- test_suite/src/lib.rs
BREAKING CHANGE:
- The main function `email_exists` now returns a Future:
```rust
pub async fn email_exists(to_email: &str, from_email: &str) -> SingleEmail {}
```
- The `SmtpError::SmtpError` has been renamed to `SmtpError::LettreError` to show the underlying error more correctly (i.e., coming from `lettre` crate).
- The `BlockedByISP` error has been removed. Instead, you'll see e.g. `"connection refused"`, or whatever is returned by the SMTP server:
```json
{
// ...,
"smtp": {
"error": {
"type": "LettreError",
"message": "connection refused"
}
},
}
```
> refactor: Use futures

- README.md
This commit fixes the println statement in "Usage as a Library" by turning :? into a string literal.
> chore: Fix library example on README

- Cargo.lock
- Cargo.toml
- Dockerfile
- README.md
- core/Cargo.toml
- core/src/lib.rs
- core/src/mx.rs
- core/src/smtp.rs
- core/src/syntax.rs
- core/src/util/email_input.rs
- core/src/util/ser_with_display.rs
- src/cli.yml
- src/http.rs
- src/main.rs
- test_suite/Cargo.toml
- test_suite/src/lib.rs
BREAKING CHANGE:
`email_exists` only takes one input now, an `EmailInput` which is built using the builder pattern.
```diff
- use check_if_email_exists::email_exists;
+ use check_if_email_exists::{email_exists, EmailInput};
- email_exists("someone@gmail.com", "user@example.org");
+ email_exists(
+   EmailInput::new("someone@gmail.com".to_string()).from_email("user@example.org".to_string())
+ )
```
`EmailInput` additionally takes a `hello_name()` method, which is used to set the name in the EHLO smtp command.
`--from` in CLI has been replaced with `--from-email`.
> feat: Use builder pattern for EmailInput

- .editorconfig
- .github/workflows/pr.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- Dockerfile
- README.md
- ci/script.sh
- core/Cargo.toml
- core/src/lib.rs
- core/src/misc.rs
- core/src/mx.rs
- core/src/smtp.rs
- core/src/syntax.rs
- core/src/util/constants.rs
- core/src/util/input.rs
- core/src/util/input_output.rs
- core/src/util/mod.rs
- core/src/util/ser_with_display.rs
- src/cli.yml
- src/http.rs
- src/main.rs
- test_suite/Cargo.toml
- test_suite/src/fixtures/foo.json
- test_suite/src/fixtures/foo@bar.baz.json
- test_suite/src/fixtures/foo@bar.json
- test_suite/src/fixtures/someone@gmail.com.json
- test_suite/src/lib.rs
BREAKING CHANGE:
This new version includes an overhaul of the codebase, mainly to prepare the groundwork for the upcoming work on bulk validation. These changes include:
- The main function `email_exists` has been renamed to `check_email`:
```diff
- email_exists(&input).await;
+ check_email(&input).await;
```
- The input `EmailInput` has been renamed to `CheckEmailInput`. Its `::new()` method, instead of taking a single `String`, now takes `Vec<String>`.
- The output `SingleEmail` has been renamed to `CheckEmailOutput`. The main function `check_emails` now returns a `Vec<CheckEmailOutput>`.
```rust
pub async fn check_email(inputs: &CheckEmailInput) -> Vec<CheckEmailOutput>
```
- The `syntax` field in `CheckEmailOutput` is no longer a `Result<SyntaxDetails, SyntaxError>`, but only …
> refactor!: Rename main function to `check_email`

- src/http.rs
I think your intention was to receive `to_emails` in a vector, so I'd suggest this change.
(The README also says `to_emails`, instead of `to_email`)
Thank you for this awesome project btw :)
> fix: http request body

- Cargo.lock
- Cargo.toml
- Dockerfile
- README.md
- core/Cargo.toml
- core/src/smtp/mod.rs
- test_suite/Cargo.toml
> fix: Don't check inputted email if catch-all

- core/src/smtp/mod.rs
Fixes #771 
This PR makes deliverability check by checking the response code to be successfult for a `RCPT TO` command. The whole reasoning is described in the source code:
> According to [RFC 5321], [`RCPT TO` command][RCPT TO] succeeds only with `250` and `251` codes: <https://tools.ietf.org/html/rfc5321#page-56>
> 
> Where the `251` code is used for forwarding, which is not our case, because we always deliver to the SMTP server hosting the address itself.
> 
> So, if [`response.is_positive()`][2] (which is [a condition for returning `Ok`][1] from the `command()` method above), then delivery succeeds, accordingly to [RFC 5321].
[RFC 5321]: https://tools.ietf.org/html/rfc5321
[RCPT TO]: https://tools.ietf.org/html/rfc5321#section-4.1.1.3
[1]: …
> Check deliverability using successful response code instead of message parsing

- core/src/smtp/mod.rs
Fixes #794 
Recreates `SmtpClient` if second SMTP commabd returns `io: incomplete` error.
Unfortunately, due to https://github.com/async-email/async-smtp/issues/37 we're unable check it earlier with `SmtpClient::is_connected()`.
> Reconnect auto-closed SMTP connections by foreign server

- .travis.yml
I got limited free credits for Travis, so only using them for building release binaries, not on PRs.
I'm also looking to switch to Github Actions: #904
> ci: Only run Travis on release tags

- .github/workflows/pr.yml
- CHANGELOG.md
- Dockerfile
- README.md
- core/src/lib.rs
- core/src/smtp/mod.rs
- core/src/util/input_output.rs
- src/http.rs
- src/main.rs
It was confusing to have:
- `input.from_email` to get the `from_email` config
- `input.from_email("...")` to set the `from_email` config.
This PR adds `set_` prefix for all setters:
```rust
input.set_from_email("...") // set from_email
```
The old setters are not removed, only deprecated.
> feat: Add `CheckEmailInput` setter `set_` prefix to differentiate with accessing fields

- core/src/mx.rs
Closes: https://github.com/reacherhq/check-if-email-exists/issues/977
This PR changes the DNS resolver so that the host configuration is used. I believe this is the configuration which allows for most customisation since each user can configure nameservers whichever way they want. I think it's also the solution which complies the most with the principle of least astonishment
Before the change, when checking `"someone@gmail.com"`, I was getting:
```
[2021-09-29T14:19:53Z DEBUG trust_dns_proto::xfer::dns_handle] querying: gmail.com MX
[2021-09-29T14:19:53Z DEBUG trust_dns_resolver::name_server::name_server_pool] sending request: [Query { name: Name { is_fqdn: false, label_data: [103, 109, 97, 105, 108, 99, 111, 109], label_ends: [5, 8] }, query_type: MX, query_class: IN }] …
```
> use DNS nameservers as configured in host machine

- cli/README.md
- cli/src/main.rs
- core/src/smtp/connect.rs
- core/src/smtp/error.rs
- core/src/smtp/gmail.rs
- core/src/smtp/http_api.rs
- core/src/smtp/mod.rs
- core/src/smtp/yahoo.rs
- core/src/util/input_output.rs
- check the validity of `gmail.com`/`googlemail.com` email addresses via the method outlined [here](https://blog.0day.rocks/abusing-gmail-to-get-previously-unlisted-e-mail-addresses-41544b62b2).
- run only via the `--gmail-use-api`/`gmail_use_api` flags (defaulting to `false`.)
relates #937
> feat: additional Gmail validation

- cli/src/main.rs
- core/src/smtp/hotmail.rs
- core/src/smtp/mod.rs
- core/src/util/input_output.rs
- check the validity of Outlook/Office 365 email addresses via the method outlined [here](https://www.trustedsec.com/blog/achieving-passive-user-enumeration-with-onedrive/).
- run only via the `--outlook-use-api` flags (defaulting to `false`.)
relates #937
> feat: add Outlook HTTP API validation

- core/src/smtp/error.rs
- core/src/smtp/microsoft/hotmail.rs
- core/src/smtp/microsoft/microsoft365.rs
- core/src/smtp/microsoft/mod.rs
- core/src/smtp/mod.rs
`hotmail` was previously behind the `headless` feature which, if disabled, breaks the Microsoft 365 API functionality.
refactor these into a `microsoft` module, leaving the `hotmail` module behind the `headless` feature and allowing the Microsoft 365 API to exist separately.
fixes #1203 
---
I've verified that the Microsoft 365 API behaviour is still working in all previously-tested scenarios. 
Someone more familiar with the Hotmail `headless` feature might want to put that through its paces though…?
> fix: split Microsoft 365/Hotmail functionality

- backend/tests/check_email.rs
- core/src/lib.rs
- core/src/normalize.rs
- core/src/syntax.rs
- core/src/util/input_output.rs
- normalise Gmail addresses:
- remove subaddresses (i.e. parts after a `+` in the username.)
- remove dots/periods (this does assume the email is valid, so won't check for double-periods, which are [invalid](https://support.google.com/mail/answer/9211434?hl=en-GB).)
- lower-case usernames.
- standardise on `gmail.com`.
- include this in `syntax.normalized_email` in the output.
relates #952
> feat: add email address normalisation

- Cargo.lock
- backend/openapi.json
- backend/tests/check_email.rs
- core/Cargo.toml
- core/src/lib.rs
- core/src/smtp/connect.rs
- core/src/smtp/mod.rs
- core/src/smtp/outlook/headless.rs
- core/src/smtp/outlook/microsoft365.rs
- core/src/smtp/yahoo/api.rs
- core/src/smtp/yahoo/headless.rs
- core/src/util/input_output.rs
> feat: Add debug information about each email verification

- backend/src/worker/check_email.rs
- core/src/rules.json
- core/src/util/input_output.rs
Vercel functions (used by https://app.reacher.email) usually timeout with a 504 error within less than 60s. So we should absolutely make a verification less than that.
After some testing, Reacher performs better with this setting:
- each SMTP connection times out after 45s, but we don't retry
over this previous setting
- each SMTP connection times out after ~20s, but we do retry once (to avoid greylisting in some rare cases)
Changing the default behaviour in this PR.
> fix!(core): Bump timeout to 45s, set retries to 1

- core/src/util/input_output.rs
I get this bug:
```rust
Compiling pwned v0.5.0
Compiling check-if-email-exists v0.9.1 (https://github.com/reacherhq/check-if-email-exists?rev=5ca9097#5ca9097d)
error[E0062]: field `yahoo_verif_method` specified more than once
--> /Users/khanh/.cargo/git/checkouts/check-if-email-exists-c4445d2e2cd9a1bc/5ca9097/core/src/util/input_output.rs:252:4
|
247 |             yahoo_verif_method: YahooVerifMethod::Api,
|             ----------------------------------------- first use of `yahoo_verif_method`
...
252 |             yahoo_verif_method: HotmailVerifMethod::Smtp,
|             ^^^^^^^^^^^^^^^^^^ used more than once
error[E0277]: the trait bound `DateTime<Utc>: Deserialize<'_>` is not satisfied
```
> Fix duplicate `yahoo_verif_method` field in default() inputs

- backend/src/http/v0/bulk/post.rs
Hi! 👋
I noticed the current content length limit of 4KB for the bulk validation endpoint is quite restrictive for real-world usage. I've increased it to 50MB to better accommodate bulk email validation requests.
This change makes the endpoint more practical for validating larger sets of emails in a single request.
Let me know if you'd like me to make any adjustments!
> Increase content length limit for bulk validation endpoint

- cli/src/main.rs
The CLI was not working because the call was made with hello-name an from-email inverted. This PR solves this issue.
> fix: Fixed inverted hello-name and from-email in CLI
